version: '3.7'
services:
    db:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=db
      ports:
        - 5432:5432
      volumes: 
        - ./data:/var/lib/postgresql/data
        - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        - ./scripts/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    web:
      build: .
      volumes:
        - .:/code
      ports:
        - "5000:5000"
      env_file:
        - .env  
      depends_on:
        - db     