version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@02.2.1

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws  
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "${AWS_RESOURCE_NAME_PREFIX}-dev"
          tag: CIRCLE_BUILD_NUM
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          context: aws  
          family: "${AWS_RESOURCE_NAME_PREFIX}-service-dev"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster-dev"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_BUILD_NUM}"
